apiVersion: apps/v1
kind: Deployment

metadata:
  name: organic-ghee-deployment

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: organic-ghee

  template:

    metadata:
      labels:
        app: {{ .Values.labels.app }}
        container: {{ .Values.labels.container }}

    spec:
      containers:

        - name: container: {{ .Values.labels.container }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}

          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}


---
apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}

spec:
  selector:
    app: {{ .Values.labels.app }}

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}