apiVersion: apps/v1
kind: Deployment

metadata:
  name: speakershop-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: speakershop

  template:
    metadata:
      labels:
        app: speakershop

    spec:
      containers:

      - name: speakershop-container
        image: mohitdocker241/speakershop:v1.0.0
        ports:
        - containerPort: 3000

      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service

metadata:
  name: my-service

spec:
  selector:
    app: speakershop

  ports:
  - protocol: TCP
    port: 85
    targetPort: 80

  type: ClusterIP